### ISSUE TITLE
Deploy fails due to version API is no longer working

### ISSUE THREAD

**Issue by trungdtbk** [Requarks/wiki-heroku#18]
https://beta.requarks.io/api/version/stable does not exist

**Comment by gubacelar** [comment]
Same here

**Comment by gubacelar** [comment]
In install.sh I change

`VERSION=$(curl -L -s -S https://beta.requarks.io/api/version/stable)` to
`VERSION=$(curl -L -s -S https://raw.githubusercontent.com/Requarks/wiki-v1/master/CURRENT)`

It install ok, but git not working and data is lost after dynos restart.

**Comment by christopinka** [comment]
tried antoligy. Gets further with deploy but open fails with

```2019-03-26T20:43:39.355633+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
2019-03-26T20:43:39.355635+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
2019-03-26T20:43:39.355637+00:00 app[web.1]:     at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
2019-03-26T20:43:39.355639+00:00 app[web.1]:     at internal/main/run_main_module.js:21:11
2019-03-26T20:43:41.140889+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=devnoops-wiki.herokuapp.com request_id=79be91c0-0717-432a-818e-34bc468abaa2 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https
2019-03-26T20:43:41.972042+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=devnoops-wiki.herokuapp.com request_id=ec049068-a0d2-4615-87e7-fc2f43179020 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https
2019-03-26T20:43:49.404485+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=devnoops-wiki.herokuapp.com request_id=f998775b-6a94-49af-97ae-8924ca8763a0 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https
2019-03-26T20:43:50.149348+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=devnoops-wiki.herokuapp.com request_id=75d32ddb-0091-41f9-b839-c0eb916cd0e6 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https
2019-03-26T20:46:06.573504+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=devnoops-wiki.herokuapp.com request_id=f382cc51-491a-46df-9a7e-43171d446cb5 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https
2019-03-26T20:46:07.084486+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=devnoops-wiki.herokuapp.com request_id=89f3e755-9d94-4ab8-bbdb-e770839f5754 fwd="71.183.233.250" dyno= connect= service= status=503 bytes= protocol=https```

**Comment by christopinka** [comment]
also not clear how to setup oauth if needed

**Comment by gubacelar** [comment]
> Deploy gets further with antoligy. Not clear how to setup oauth. Attempted setting up deploy keys and have local auth provider set to true. Getting error
> 
> `2019-03-26T20:58:34.190207+00:00 app[web.1]: Error: You must enable at least 1 authentication strategy!`

What have you change?

Just clone this project, and add your heroku git url

git remote add heroku https://git.heroku.com/my-wiki.git
git push heroku, or if you are on a branch, git push heroku mybranch:master

Also you need to change install.sh

VERSION=$(curl -L -s -S https://beta.requarks.io/api/version/stable) to
VERSION=$(curl -L -s -S https://raw.githubusercontent.com/Requarks/wiki-v1/master/CURRENT)

it should work.

**Comment by christopinka** [comment]
What about changes to app.json and/or config.yml?

Just tried:

$ git clone https://github.com/Requarks/wiki-heroku.git
$ heroku create devnoops-wiki
edit install.sh
$ git commit -am "update version"
$ heroku open

getting: 

 'Application Error'
$ heroku logs


` app[web.1]: 2019-03-27T15:08:17.275Z - error: [SERVER] Failed to connect to MongoDB instance.
2019-03-27T15:08:17.276635+00:00 app[web.1]: /app/wiki/node_modules/mongoose/lib/connection.js:723
2019-03-27T15:08:17.276638+00:00 app[web.1]: throw error;
2019-03-27T15:08:17.276640+00:00 app[web.1]: ^
2019-03-27T15:08:17.276642+00:00 app[web.1]: 
2019-03-27T15:08:17.276644+00:00 app[web.1]: Error: Invalid mongodb uri. Must begin with "mongodb://"
2019-03-27T15:08:17.276646+00:00 app[web.1]: Received: undefined`

**Comment by gubacelar** [comment]
Sorry, 
You need to create the heroku app from the wiki button first:

https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FRequarks%2Fwiki-heroku&template=https%3A%2F%2Fgithub.com%2Frequarks%2Fwiki-heroku

You will notice that the build will fail, and then you clone project, change the remote for your heroku git remote.

No need to change app.json or  config.yml, you will set your variables on that link for app creation,
after you change install.sh and push it, if your variables are correct you will have access to your wiki.

Creating the app with that url you will have all dynos already running for you.

If you dont want to use heroku pannel to set your variables, you can set then on app.json and probably will work.

**Comment by christopinka** [comment]
I chose the edit app.json route
$ git commit -am ""
$ git push heroku
$ heroku open
page has 'Application Error'
$ heroku logs

' app[web.1]: 2019-03-27T18:08:26.644Z - error: [SERVER] Failed to connect to MongoDB instance.
2019-03-27T18:08:26.645820+00:00 app[web.1]: /app/wiki/node_modules/mongoose/lib/connection.js:723
2019-03-27T18:08:26.645824+00:00 app[web.1]: throw error;
2019-03-27T18:08:26.645826+00:00 app[web.1]: ^
2019-03-27T18:08:26.645827+00:00 app[web.1]: 
2019-03-27T18:08:26.645829+00:00 app[web.1]: Error: Invalid mongodb uri. Must begin with "mongodb://"
2019-03-27T18:08:26.645831+00:00 app[web.1]: Received: undefined'

**Comment by christopinka** [comment]
I just provisioned mLab manually and the app is up.

**Comment by gubacelar** [comment]
If you look on your app.json

`    "WIKI_ADMIN_EMAIL": {
      "description": "Email to use during root administrator account creation (default password: admin123)",
      "value": "marty@example.com"
    },`
**default password: admin123)**

You can enter in your Mongo's Dyno and check if there's any users.
I belive you have to enter a new user manually.

If you cant cript your password, you maybe can try install locally(https://github.com/Requarks/wiki-v1)
and copy user and password from your local mongo to your heroku dyno mongo.

**Comment by christopinka** [comment]
ok. Thanks.

Looks like this might be a good idea for connection to github/gitlab 

https://elements.heroku.com/buildpacks/poetic-labs/git-ssh-key-buildpack

**Comment by christopinka** [comment]
No love. Oh well, I tried. Too bad, screenshots look good. Is there a demo site?

**Comment by NGPixel** [comment]
Fixed install script.
