### ISSUE TITLE
"Error: Cannot find module '/wiki/heroku'"

### ISSUE THREAD

**Issue by trulyWHOOOP** [Requarks/wiki-heroku#27]
Hi,
I cannot run wiki on heroku, I get this issue

```
Error: Cannot find module '/wiki/heroku'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by NGPixel** [comment]
Have you followed the instructions for Heroku?

https://docs.requarks.io/install/heroku

**Comment by trulyWHOOOP** [comment]
Yep

**Comment by trulyWHOOOP** [comment]
Someone help please!

**Comment by Johann-L-Pickard** [comment]
A new installation from the button from https://docs.requarks.io/install/heroku , no longer works, it worked before, but does not.
