### ISSUE TITLE
Error: Cannot find module '/app/wiki/server'

### ISSUE THREAD

**Issue by marcdubs** [Requarks/wiki-heroku#8]
On a clean install in Heroku I'm getting this error:
```
2017-10-02T03:19:58.217691+00:00 heroku[web.1]: Starting process with command `cd wiki && node server`
2017-10-02T03:20:00.776259+00:00 app[web.1]: module.js:473
2017-10-02T03:20:00.776305+00:00 app[web.1]:       throw err;
2017-10-02T03:20:00.776306+00:00 app[web.1]:       ^
2017-10-02T03:20:00.776307+00:00 app[web.1]:
2017-10-02T03:20:00.776309+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:527:15)
2017-10-02T03:20:00.776308+00:00 app[web.1]: Error: Cannot find module '/app/wiki/server'
2017-10-02T03:20:00.776309+00:00 app[web.1]:     at Function.Module._load (module.js:453:25)
2017-10-02T03:20:00.776310+00:00 app[web.1]:     at Function.Module.runMain (module.js:665:10)
2017-10-02T03:20:00.776311+00:00 app[web.1]:     at startup (bootstrap_node.js:187:16)
2017-10-02T03:20:00.776311+00:00 app[web.1]:     at bootstrap_node.js:607:3
2017-10-02T03:20:00.868102+00:00 heroku[web.1]: State changed from starting to crashed
```

Any ideas?

**Comment by NGPixel** [comment]
Fixed. Install again.

**Comment by dougbradbury** [comment]
I'm seeing the same thing on a recent install

**Comment by leonardogabrich** [comment]
Me too!
